### ISSUE TITLE
Error building with GCC 4.7

### ISSUE THREAD

**Issue by zloidemon** [rescrv/po6#5]
If it build with gcc4.7 you can catch it error, but with 4.6 all works.

```
$ gmake
gmake  all-am
gmake[1]: Entering directory `/var/tmp/usr/ports.svn/sysutils/replicant/work/replicant-0.2.1'
  CXX    common/libreplicant_la-bootstrap.lo
In file included from /usr/local/include/po6/net/location.h:36:0,
                 from /usr/local/include/po6/net/hostname.h:40,
                 from /usr/local/include/busybee_single.h:35,
                 from common/bootstrap.cc:40:
/usr/local/include/po6/net/ipaddr.h: In static member function 'static po6::net::ipaddr po6::net::ipaddr::ANY()':
/usr/local/include/po6/net/ipaddr.h:62:45: error: 'u_int32_t' was not declared in this scope
gmake[1]: *** [common/libreplicant_la-bootstrap.lo] Fehler 1
```
